### ISSUE TITLE
Create a simple text format that can represent a workflow and be converted to a Dask DAG

### ISSUE THREAD

**Issue by jerowe** [Quansight-Labs/dask-jobqueue#1]
We need a parser that can take as it's input a text file with bash commands and create a Dask HighLevelGraph.

Jobs are normally grouped together by analysis type (QC, filter, preprocess, align) and/or compute resources.

Simple Example with job only dependencies. In this example, all tasks in job_1 must complete before any in job_2 can complete.

```
#HPC jobname=job_1
#HPC walltime=10:00:00
#HPC mem=32GB
#HPC cpus_per_task=1
job_1_task_1
job_1_task_2
job_1_task_3
job_1_task_4

#HPC jobname=job_2
#HPC walltime=10:00:00
#HPC mem=32GB
#HPC cpus_per_task=1
#HPC deps=job_1
job_2_task_1
job_2_task_2
job_2_task_3
job_2_task_4
```

Example with Task Dependencies

I think Dharhas would have some really good insight into how this should be done.

When I would submit something like this on SLURM I would use array dependencies. Essentially, instead of submitting a single job N times you submit a job once that is itself a for loop that executes N times. 

Jobs can depend on jobs, and tasks within the job can depend upon tasks in another job. 

I don't think that this needs to be translated specifically into job arrays, but can be handled by the Dask Scheduler itself.

```
#HPC jobname=job_1
#HPC walltime=10:00:00
#HPC mem=32GB
#HPC cpus_per_task=1

#HPC task_tags=task_1
job_1_task_1
#HPC task_tags=task_2
job_1_task_2
#HPC task_tags=task_3
job_1_task_3
#HPC task_tags=task_4
job_1_task_4

#HPC jobname=job_2
#HPC deps=job_1
#HPC walltime=10:00:00
#HPC mem=32GB
#HPC cpus_per_task=1

#HPC task_tags=task_1
job_2_task_1
#HPC task_tags=task_2
job_2_task_2
#HPC task_tags=task_3
job_2_task_3
#HPC task_tags=task_1
job_2_task_4

#HPC jobname=job_3
#HPC deps=job_3
#HPC walltime=10:00:00
#HPC mem=32GB
#HPC cpus_per_task=1

job_3_task_1
job_3_task_2
job_3_task_3
job_3_task_4
```

**Comment by dharhas** [comment]
So the above essentially is defines 3 separate job submission to slurm, each for 10 hrs. 

Options:

a) Do exactly the above. Slurm can already handle this why do we need Dask.

b) Use Slurm and Dask. Use slurm to manage the interjob dependencies, each job will launch a dask cluster and run the intrajob tasks in parallel. Not sure that this has much benefit.

c) Only use slurm to launch a dask cluster of sufficient size and duration. Handle everything else through the dask scheduler including dependencies.

To me (c) makes the most sense and is the most portable to other systems. The only issue is if you have wallclock limitations. And in that case, looking at this issue might make sense (essentially keep starting new workers when old ones expire due to wallclock expiration): 

https://github.com/dask/dask-jobqueue/issues/122

Also if we decide on (3), we can also consider dropping the format listed above which is very slurm specific and use a nicer format to describe dependencies.

i.e. we separate the definition of resources from the definition of the workflow.

**Comment by jerowe** [comment]
@dharhas  I like option 3 the best too. I think if we can keep things platform (HPC, Kubernetes, ECS) agnostic we should.

I'm all for a new a syntax. In a perfect world I think this could get split into 2 components:

1. A **very** simple syntax to define jobs / deps / resources, and that would be for the people that aren't so computational and this would just take care of it for them. 
2. A nicer developers API that is super shiny and nice

**Comment by Adam-D-Lewis** [comment]
So if I understand correctly, it seems like the workflow file wouldn't need #HPC walltime, HPC mem=32GB, or HPC cpus_per_task=1, since those details will be specified separately, right?

While we still might change the workflow file format (see https://github.com/Quansight-Labs/dask-jobqueue/issues/3), I want to see if I'm on the same page as others as to how the dask graph will look.  My question is at the bottom.

Workflow File Example
==================
Workflow File
------------------
```sh
#HPC jobname=job0
#HPC task_tags=task_0
job1_0_bash_script_string
#HPC task_tags=task_1
job1_1_bash_script_string

#HPC jobname=job1
#HPC deps=job0

#HPC task_tags=task_0
job1_0_bash_script_string

#HPC jobname=job2
#HPC deps=job1
job2_0_bash_script_string
job2_1_bash_script_string
job2_2_bash_script_string
```

Corresponding Dask High Level Graph
----------------------------------------------------
```python3
layers = {
   'job0': {
            ('job0', 0): (subprocess.run, job0_0_bash_script_string),
            ('job0', 1): (subprocess.run, job0_1_bash_script_string),
           }

   'job1': {
            ('job1', 0): (subprocess.run, job1_0_bash_script_string)
           }

   'job2': {
             ('job2', 0): (subprocess.run, job2_0_bash_script_string),
             ('job2', 1): (subprocess.run, job2_1_bash_script_string),
             ('job2', 2): (subprocess.run, job2_2_bash_script_string),
           }
}

dependencies = {'job0': set(),
                'job1': {'job0'},
                'job2': {'job1'}}

graph = HighLevelGraph(layers, dependencies)
```

Is this how others imagine the Dask graphs looking with subprocess.run functions to be run on all the shell string commands?

**Comment by dharhas** [comment]
Rename this issue (See https://github.com/Quansight-Labs/dask-jobqueue/issues/4)

I think we should rename to something like `Create a simple text format that can represent a workflow and be converted to a Dask DAG`.

**Comment by dharhas** [comment]
@jerowe would using a yaml style config similar to this be too high a barrier for our target audience. The advantage is parsing, error checking etc:

```yaml
example_dag1:
  default_args:
    owner: 'example_owner'
    start_date: 2018-01-01
  schedule_interval: '0 3 * * *'
  description: 'this is an example dag!'
  tasks:
    task_1:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: 'echo 1'
    task_2:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: 'echo 2'
      dependencies: [task_1]
    task_3:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: 'echo 3'
      dependencies: [task_1]
```

We wouldn't need all the fields & complexity but using something like yaml avoids having to build a parser. plus you get syntax highlighting etc when you built it and we could build a linter easily to check the DAG and display it. Your earlier example would end up being:

```yaml
my_job_name:
  resources:
     cpu: 10
     queue: normal 
  tasks:
    read_data:
      bash_commands: 
        - bash_script_string_1
        - bash_script_string_2
    process_data:
      bash_commands:
         - bash_script_string_3
      dependencies: [read_data]
    plot_data:
      bash_commands:
         - bash_script_string_4
     dependencies: [process_data]
     description: plots the data and saves it to disk
```

**Comment by jerowe** [comment]
@balast thanks!

I totally understand the advantages of using a YAML file over a plain text. YAML is tricky for people with no computational background because they will try to do things like open Word or Google docs and work with them and then the whitespace gets all messed up.

Would it be possible to have something that could read .ini AND .yaml files? .ini is easier for non techy folks because there are no weird whitespace issues. 

Secondly, I know I included a link to Airflow in that doc and probably confused the issue. I wasn't meaning that we should use Airflow to create DAGs. I just like their bash executor because it buffers the output. Some programs create a LONG stream of stdout/stderr.

**Comment by dharhas** [comment]
@jerowe 

The whitespace problem is real for folks using non yaml aware editors. .ini has its drawbacks but is doable. How about `toml` (https://github.com/toml-lang/toml), its the new format being used by python setup files and is a nice mix of readability and whitespace/indentation is optional. It kinda takes the best parts of yaml and ini.

example:

```toml
# This is a TOML document.

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]
```

Regarding the BashWrapper. Buffering the output is a good reason to use one. My point was that this is two issues that are not related.

issue a) Define a workflow with a text file
issue b) Have a nice way of calling a bash cmd

**Comment by Adam-D-Lewis** [comment]
I'm copying over from https://github.com/Quansight-Labs/dask-jobqueue/issues/3#issuecomment-604429704 since that issue was closed as a duplicate.

From @jerowe: 
***
I think something like this would be more natural to HPC users - 

```
- jobs
  - name: job_1
  - resources:
# I got this from the Dask JobQueue how this works
#        cluster = PBSCluster(  # <-- scheduler started here
#          cores=24,
#          memory='100GB',
#          shebang='#!/usr/bin/env zsh',  # default is bash
#          processes=6,
#          local_directory='$TMPDIR',
#          resource_spec='select=1:ncpus=24:mem=100GB',
#          queue='regular',
#          project='my-project',
#          walltime='02:00:00',
#          )
      - mem: 100GB
      - processes: 6
      - walltime: '02:00:00'
      - queue: 'regular'
      # etc
  - tasks:
      - shell: echo "hello world from task 1"
      - shell: echo "hello world from task 2"
  - name: job_2
  - depends:
      - job_1
  - tasks:
      - shell: echo "hello world from task 1"
      - shell: echo "hello world from task 2"

```

I think [this](https://jobqueue.dask.org/en/latest/howitworks.html) page is the most straightforward for a translation of JobQueue -> Dask Worker. 

Then I think the dask-worker process is smart enough to figure out that it has 6 processes and run the 6 tasks concurrently. 

I do really like the idea of having the shell there. If there was interest there could be python executors in there as well.

**Comment by Adam-D-Lewis** [comment]
I'm copying over from https://github.com/Quansight-Labs/dask-jobqueue/issues/3#issuecomment-604458486 since that issue was closed as a duplicate.  
From @dharhas:
***
So yaml is easy to read but you need to be whitespace aware, toml and ini are harder to read and construct but are not whitespace sensitive. JSON is hard to read and has lots of brackets you have to match correctly.

@jerowe in your jobqueue code above you have 6 processes with 4 threads each for a total of 24 tasks that can happen at the same time. Depending on your workload type the performance will change depending on whether you use more threads (i.e. 1 process/24 threads) or more processes (i.e. 24 processes each with 1 thread). Since we are just calling bash scripts I don't think it will matter.

**Comment by Adam-D-Lewis** [comment]
I've attached an example toml workflow file.  It seems like it would be a bit cumbersome to allow tasks to be dependent on other tasks in the same job.  Is that necessary?  Comments?  

```toml
# Workflow File

[resources]
cluster_type = "SLURMCluster" # Could be any cluster type supported by Job Queue, but obviously must match the Workload Manager used by the HPC Cluster.
n_workers = 10

[resources.worker]
# per worker params (any of those supported by that cluster type in Jobqueue)
cores = 8
processes = 4
memory = "16GB"
project = "MyProject"
Walltime = "01:00:00"
queue = "normal"

[job1]
[job1.tasks]
task1="bash_script_string_1"
task2="bash_script_string_2"
task3="bash_script_string_3"
task4="bash_script_string_4"
    
[job2]
depends = ["job1", "anotherjob"]
[job2.tasks]
task1="bash_script_string_5"
task2="bash_script_string_6"
task3="bash_script_string_7"
task4="bash_script_string_8"
```
