### ISSUE TITLE
Workflow File Format and Dask High Level Graph Implementation

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight-Labs/dask-jobqueue#3]
What should the filetype/specs of the workflow file be?

**Comment by Adam-D-Lewis** [comment]
I'm not set on any filetype in particular, but making this suggestion to help spur conversation/decisions.

```yaml
step: stepname3
  - depends:
    - stepname1 (not shown)
    - stepname2 (not shown)
  - task: taskname1
    - shell: bash_command && \
another bash_command
  - task: taskname2
    - depends:
      - taskname1 (these dependencies would only be tasks within the same step)
    - shell: bash_command && \
another bash_command
```

Each step would be a layer in a Dask High Level Graph, and so if a task depends on a task in a  previous step, it would be an interstep dependency.

I called the segments "steps" instead of "jobs", since I don't believe these are jobs in the sense that HPC folks are used to.  The "jobs" are actually the Dask Workers, I believe, based on https://www.youtube.com/watch?v=FXsgmwpRExM&t=400s.
